name: "cls"
platform: "ensemble"
max_batch_size: 8

input [
    {
        name: "input_text"
        data_type: TYPE_STRING
        dims: [-1]
    }
]

output [
    {
        name: "class"
        data_type: TYPE_STRING
        dims: [-1, 3]
    },
    {
        name: "prob"
        data_type: TYPE_FP32
        dims: [-1, 3]
    }
]

ensemble_scheduling {
    step [
        {
            model_name: "pre_processing"
            model_version: -1
            input_map {
                key: "input_text"
                value: "input_text"
            }
            output_map [
                {
                    key: "input_ids"
                    value: "input_ids"
                },
                {
                    key: "attention_mask"
                    value: "attention_mask"
                }
            ]
        },
        {
            model_name: "forward"
            model_version: -1
            input_map [
                {
                    key: "input_ids"
                    value: "input_ids"
                },
                {
                    key: "attention_mask"
                    value: "attention_mask"
                }
            ]
            output_map {
                key: "output__0"
                value: "output__0"
            }
        },
        {
            model_name: "post_processing"
            model_version: -1
            input_map {
                key: "output__0"
                value: "output__0"
            }
            output_map [
                {
                    key: "class"
                    value: "class"
                },
                {
                    key: "prob"
                    value: "prob"
                }
            ]
        }
    ]
}
